
-- NESTA CONSULTA, É LISTADO TODOS OS VALORES DA TABELA FUNCIONÁRIO, PARA AQUELES QUE RECEBE MAIS DE R$3000,00 REAIS.
SELECT *
FROM FUNCIONARIO
WHERE salariobruto > 3000;

-- ORDER BY COM DUAS COLUNAS
-- NESTA CONSULTA, É RETORNADO O CPF E O CARGO DO FUNCIONÁRIO ATRAVÉS DA ORDENAÇÃO EM ORDEM ASCEDENTE 
-- DA DATA DE ADMISSAO DO MESMO.
SELECT CPFFUNCIONARIO, CARGO FROM FUNCIONARIO ORDER BY DATAADMISSAO ASC;

-- JUNÇÃO COM DUAS TABELAS
-- NESTA CONSULTA, É RETORNADO AS PESSOAS QUE SÃO FUNCIONARIOS
SELECT NOMEPESSOA FROM PESSOA JOIN FUNCIONARIO ON PESSOA.CPFPESSOA = FUNCIONARIO.CPFFUNCIONARIO;

-- JUNÇÃO COM TRÊS TABELAS
-- ESTA CONSULTA RETORNA OS VALORES DAS PESSOAS ESTÃO CADASTRADAS COMO CLIENTES E QUE POSSUEM TELEFONE.
SELECT PESSOA.CPFPESSOA, NOMEPESSOA, NUMEROTELEFONE FROM (PESSOA JOIN CLIENTE ON PESSOA.CPFPESSOA = CLIENTE.CPFCLIENTE )
JOIN TELEFONE ON PESSOA.CPFPESSOA = TELEFONE.CPFPESSOA;

--GROUP BY
-- ESTA CONSULTA RETORNA QUANTIDADE DE ITENS E 
-- ESTA CONSULTA RETORNA A QUANTIDADE DE VENDAS REALIZADAS, A QUANTIDADE TOTAL DE ITENS VENDIDOS E O VALOR TOTAL DA COMPRA 
-- AGRUPADOS PELO VALOR TOTAL DA COMPRA. APENAS AS COMPRAS COM VALOR TOTAL MENOR OU IGUAL A R$150 REAIS E 
-- QUANTIDADE TOTAL DE ITENS VENDIDOS ENTRE MENOR OU IGUAL A 10 SÃO CONSIDERADAS.

SELECT COUNT(*) AS QUANTIDA_VENDA, SUM(QUANTIDADEITEM) AS quantidade_total_de_itens_vendidos, VALORTOTAL AS Valor_Total
FROM COMPRA JOIN ITEMCOMPRA ON COMPRA.NUMCUPOMFISCAL = ITEMCOMPRA.NUMCUPOMFISCAL
WHERE VALORTOTAL <= 150 AND QUANTIDADEITEM <= 10
GROUP BY VALORTOTAL;

-- GROUP BY AND HAVING
-- ESSA QUERY RETORNA A QUANTIDADE DE VENDAS REALIZADAS, O SOMATÓRIO DOS VALORES DE CADA VENDA REALIDAS POR ELE, 
-- PARA VENDAS COM VALOR MAIOR DO QUE R$50,00 REAIS. A QUANTIDADE DE VENDAS E O VALOR TOTAL DAS VENDAS SÃO 
-- AGRUPADOS PELO CPF DO FUNCIONÁRIO. A CLÁUSULA HAVING É UTILIZADA PARA FILTRAR OS RESULTADOS E RETORNAR 
-- APENAS OS FUNCIONÁRIOS QUE REALIZARAM PELO MENOS UMA VENDA.

SELECT CPFFUNCIONARIO, COUNT(*) AS quantidade_de_vendas, SUM(VALORTOTAL) AS valor_total_das_vendas
FROM COMPRA
WHERE VALORTOTAL > 50
GROUP BY CPFFUNCIONARIO
HAVING COUNT(*) >= 1;

-- LEFT, RIGHT OU FULL JOIN, OUTER JOIN

-- ESSA CONSULTA SQL USA LEFT JOIN PARA UNIR AS TABELAS PRODUTO, CARRINHO E ESTOQUE. 
-- ELA CONSULTA E RETORNA A DESCRIÇÃO DO PRODUTO, A DESCRIÇÃO DO ESTOQUE, A QUANTIDADE 
-- DE ITENS NO CARRINHO E O ID DO PRODUTO. ELA FARÁ COM QUÊ SE UM PRODUTO NÃO ESTIVER PRESENTE 
-- NO CARRINHO OU NO ESTOQUE, SERÁ INCLUÍDO NA CONSULTA, MAS AS COLUNAS CORRESPONDENTES SERÃO PREENCHIDAS COM VALORES NULOS.


SELECT p.DESCRICAOPRODUTO, E.DESCRICAOESTOQUE, c.QUANTIDADEITEM, p.CODPRODUTO
FROM PRODUTO p
LEFT JOIN CARRINHO c ON p.CODPRODUTO = c.CODPRODUTO
LEFT JOIN ESTOQUE e ON p.CODESTOQUE = e.CODESTOQUE;